language: python
python:
  - "3.7"

stages:
  - test

before_install:
  - cd ..
  # Install miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  # Update conda
  # - conda update --yes conda
  - conda update -y -n base conda setuptools
  - conda info -a
  # Set git info
  - git config --global user.name "Travis Deploy"
  - git config --global user.email "alongd@mit.edu"

cache: pip

jobs:
  include:
    - stage: test
      install:
        - git clone https://github.com/ReactionMechanismGenerator/ARC
        - cd ARC
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - cd ..
        - cd zmats
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - conda env create -q -f devtools/conda-envs/environment_test.yml
        - source activate zmats_env_tst
        - conda install -y -c conda-forge codecov
        - conda list
      script:
        - make test
        - codecov --token=ed449762-6e56-476c-ba99-dc32b3ae8cce
